# Generated by Django 3.2.8 on 2021-12-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_allquizes_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ans',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='op1',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='op2',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='op3',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='op4',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
