# Generated by Django 3.2.8 on 2021-12-30 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211230_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=122)),
                ('name', models.CharField(max_length=122)),
                ('dateStamp', models.DateField()),
                ('question', models.JSONField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.question'))),
            ],
        ),
        migrations.DeleteModel(
            name='AllQuizes',
        ),
        migrations.AddField(
            model_name='question',
            name='email',
            field=models.CharField(default=None, max_length=122),
        ),
    ]
