# Generated by Django 3.2.8 on 2022-01-07 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_album_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('quest', models.CharField(max_length=100)),
                ('ans', models.IntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizes', to='home.album')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('album', 'number')},
            },
        ),
    ]
