# Generated by Django 3.2.8 on 2022-01-08 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20220108_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllQuizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.album')),
            ],
        ),
        migrations.CreateModel(
            name='QuizFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfQuiz', models.CharField(max_length=100)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizesFinal', to='home.allquizes')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('ans', models.CharField(max_length=100)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionFinal', to='home.quizfinal')),
            ],
        ),
    ]
