# Generated by Django 3.2.8 on 2022-01-08 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_usercontainer_tutorname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allquizes',
            name='tutorName',
        ),
        migrations.RemoveField(
            model_name='questionfinal',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='quizfinal',
            name='tutor',
        ),
        migrations.DeleteModel(
            name='UserContainer',
        ),
        migrations.DeleteModel(
            name='AllQuizes',
        ),
        migrations.DeleteModel(
            name='QuestionFinal',
        ),
        migrations.DeleteModel(
            name='QuizFinal',
        ),
    ]
