# Generated by Django 3.2.8 on 2022-01-09 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20220108_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionfinal',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='quizfinal',
            name='tutor',
        ),
        migrations.DeleteModel(
            name='AllQuizes',
        ),
        migrations.DeleteModel(
            name='QuestionFinal',
        ),
        migrations.DeleteModel(
            name='QuizFinal',
        ),
        migrations.DeleteModel(
            name='UserContainer',
        ),
    ]
