# Generated by Django 3.2.9 on 2022-01-11 07:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='remark',
            field=ckeditor.fields.RichTextField(default=' '),
        ),
    ]
