# Generated by Django 3.2.8 on 2022-01-18 08:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_questionfinal_que'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionfinal',
            name='op1',
            field=ckeditor.fields.RichTextField(default=' '),
        ),
        migrations.AddField(
            model_name='questionfinal',
            name='op2',
            field=ckeditor.fields.RichTextField(default=' '),
        ),
        migrations.AddField(
            model_name='questionfinal',
            name='op3',
            field=ckeditor.fields.RichTextField(default=' '),
        ),
        migrations.AddField(
            model_name='questionfinal',
            name='op4',
            field=ckeditor.fields.RichTextField(default=' '),
        ),
    ]
