# Generated by Django 3.2.8 on 2022-01-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20220118_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizfinal',
            name='bool',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='quizfinal',
            name='timeStamp',
            field=models.DateField(default=None),
        ),
    ]
