# Generated by Django 3.2.8 on 2022-01-23 08:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20220123_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizfinal',
            name='code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.CreateModel(
            name='StudentFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfStudent', models.CharField(default=' ', max_length=100)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.quizfinal')),
            ],
        ),
    ]
