# Generated by Django 3.2.9 on 2022-01-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20220123_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionfinal',
            name='questionTimer',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='quizfinal',
            name='quizTimer',
            field=models.IntegerField(default=10),
        ),
    ]
