# Generated by Django 3.2.8 on 2022-02-15 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20220131_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnwerFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(default=' ', max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.questionfinal')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.quizfinal')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.studentfinal')),
            ],
        ),
    ]
