# Generated by Django 3.2.8 on 2022-02-15 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_anwerfinal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnwerFinal',
            new_name='AnswerFinal',
        ),
    ]
