# Generated by Django 3.2.8 on 2022-02-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_rename_anwerfinal_answerfinal'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionfinal',
            name='marks',
            field=models.IntegerField(default=10),
        ),
    ]
