# Generated by Django 3.2.9 on 2022-03-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_questionfinal_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionfinal',
            name='queImage',
            field=models.ImageField(default=None, upload_to=None),
        ),
    ]
