# Generated by Django 3.2.9 on 2022-03-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_questionfinal_queimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionfinal',
            name='queImage',
            field=models.ImageField(default=None, upload_to='img/%y'),
        ),
    ]
